// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvcosMEmB-edmS0fQFbELvYc3v6eU8UPU',
    appId: '1:505214480315:android:ffc204b98297f5877a5e9e',
    messagingSenderId: '505214480315',
    projectId: 'vibeflick-5fe5c',
    databaseURL: 'https://vibeflick-5fe5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vibeflick-5fe5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD2ejMUgrgeGd3EYTN99sGq-4IFj1RUUg',
    appId: '1:505214480315:ios:d34be285d91c2ba97a5e9e',
    messagingSenderId: '505214480315',
    projectId: 'vibeflick-5fe5c',
    databaseURL: 'https://vibeflick-5fe5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vibeflick-5fe5c.firebasestorage.app',
    androidClientId: '505214480315-fjo9a23t9eoo78vkavv4koldv1e4nbir.apps.googleusercontent.com',
    iosClientId: '505214480315-jvv1gp5nb1lorrsn3lv069k3jok2c046.apps.googleusercontent.com',
    iosBundleId: 'com.avishka.vibeflick.myVibeFlick',
  );
}
